name: CI/CD Ecom

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install required dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DEBUG: ${{secrets.DEBUG}}
          ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
          CORS_ALLOWED_ORIGINS: ${{secrets.CORS_ALLOWED_ORIGINS}}
          EMAIL_PORT: ${{secrets.EMAIL_PORT}}
          EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
          EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
        run: |
          pytest -v
