name: Push Main Branch into Production

on:
  push:
    branches:
      - main

jobs:
  push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Production
        uses: actions/checkout@v2
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          run: |
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git checkout -b production_v1
            git push origin production_v1 --force
